---
database_file: "/home/stephen/Dropbox/.timetrap.db"
round_in_seconds: 900
append_notes_delimiter: " "
formatter_search_paths:
- "/home/stephen/Dropbox/.timetrap/formatters"
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
- "/home/stephen/Dropbox/.timetrap/auto_sheets"
default_command:
auto_checkout: false
require_note: false
