#
# Generated by zgen.
# This file will be overwritten the next time you run zgen save
#

#
# Add our plugins and completions to fpath
#
fpath=(/Users/stephen/.zgen/rhysd/zsh-bundle-exec-master/ /Users/stephen/.zgen/djui/alias-tips-master/ /Users/stephen/.zgen/StackExchange/blackbox-master/ /Users/stephen/.zgen/ascii-soup/zsh-url-highlighter-master/ /Users/stephen/.zgen/Tarrasch/zsh-colors-master/ /Users/stephen/.zgen/tarruda/zsh-autosuggestions-master/ /Users/stephen/.zgen/zsh-users/zsh-syntax-highlighting-master/ /Users/stephen/.zgen/zsh-users/zsh-history-substring-search-master/ ${fpath})
