#
# Generated by zgen.
# This file will be overwritten the next time you run zgen save
#
source "/home/stephen/.zgen/robbyrussell/oh-my-zsh-master/oh-my-zsh.sh"
source "/home/stephen/.zgen/rhysd/zsh-bundle-exec-master//zsh-bundle-exec.zsh"
source "/home/stephen/.zgen/robbyrussell/oh-my-zsh-master/plugins/git/git.plugin.zsh"
source "/home/stephen/.zgen/robbyrussell/oh-my-zsh-master/plugins/ruby/ruby.plugin.zsh"
source "/home/stephen/.zgen/robbyrussell/oh-my-zsh-master/plugins/command-not-found/command-not-found.plugin.zsh"
source "/home/stephen/.zgen/djui/alias-tips-master//alias-tips.plugin.zsh"
source "/home/stephen/.zgen/StackExchange/blackbox-master//blackbox.plugin.zsh"
source "/home/stephen/.zgen/Tarrasch/zsh-colors-master//colors.plugin.zsh"
source "/home/stephen/.zgen/tarruda/zsh-autosuggestions-master//autosuggestions.plugin.zsh"
source "/home/stephen/.zgen/robbyrussell/oh-my-zsh-master/themes/fox.zsh-theme"
source "/home/stephen/.zgen/zsh-users/zsh-syntax-highlighting-master//zsh-syntax-highlighting.plugin.zsh"
source "/home/stephen/.zgen/zsh-users/zsh-history-substring-search-master//zsh-history-substring-search.plugin.zsh"

#
# Add our plugins and completions to fpath
#
fpath=(/home/stephen/.zgen/robbyrussell/oh-my-zsh-master /home/stephen/.zgen/rhysd/zsh-bundle-exec-master /home/stephen/.zgen/robbyrussell/oh-my-zsh-master/plugins/git /home/stephen/.zgen/robbyrussell/oh-my-zsh-master/plugins/ruby /home/stephen/.zgen/robbyrussell/oh-my-zsh-master/plugins/heroku /home/stephen/.zgen/robbyrussell/oh-my-zsh-master/plugins/command-not-found /home/stephen/.zgen/djui/alias-tips-master /home/stephen/.zgen/StackExchange/blackbox-master /home/stephen/.zgen/ascii-soup/zsh-url-highlighter-master/ /home/stephen/.zgen/Tarrasch/zsh-colors-master /home/stephen/.zgen/tarruda/zsh-autosuggestions-master /home/stephen/.zgen/robbyrussell/oh-my-zsh-master/themes /home/stephen/.zgen/zsh-users/zsh-syntax-highlighting-master /home/stephen/.zgen/zsh-users/zsh-completions-master/src /home/stephen/.zgen/zsh-users/zsh-history-substring-search-master ${fpath})
